sudo: required

language: go

go:
    - 1.7
    - 1.8
    - tip

services:
    - docker

before_install:
    - docker --version

install:
    - go get github.com/Masterminds/glide
    - glide install

script:
    - go test $(glide novendor)
    - docker build . -t genesor/cochonou

after_success:
    - docker login quay.io -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    - docker push genesor/cochonou
