sudo: required

language: go

go:
    - 1.8

services:
    - docker

env:
  global:
    - COMMIT=${TRAVIS_COMMIT}
    - BRANCH=${TRAVIS_BRANCH}

before_install:
    - sudo apt-get update
    - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-engine
    - if [ "$BRANCH" == "master" ]; then
        export CUSTOM_TAG=$COMMIT;
      else
        export CUSTOM_TAG=$BRANCH;
      fi


install:
    - go get github.com/Masterminds/glide
    - glide install

script:
    - make test
    - docker login quay.io -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    - if [ "$BRANCH" == "master" ]; then
        docker build -t quay.io/genesor/cochonou .;
        docker tag quay.io/genesor/cochonou:latest quay.io/genesor/cochonou:$CUSTOM_TAG;
        docker push quay.io/genesor/cochonou;
      else
        docker build -t quay.io/genesor/cochonou:$CUSTOM_TAG .;
        docker push quay.io/genesor/cochonou:$CUSTOM_TAG;
      fi
